name: py39 linux,win+macos
on:
  push:
    branches:
      - 'develop/*'
  workflow_dispatch:
env:
  PYTHON_VERSION: '3.9'
  PREFIX_TOX: 'py39-test-'
jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toxenv: [pytestoldest, pytest50, pytest51, pytest60, pytest62]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{  env.PYTHON_VERSION }}
      - name: Install pipx
        shell: bash
        run: pipx --version || python -m pip install --user pipx
      - name: Pip Cache
        id: pip-cache
        shell: bash
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{matrix.toxenv}}-${{ hashFiles('**/setup.cfg', '**/tox.ini') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{matrix.toxenv}}-
      - name: Install Tox
        run: pipx install tox --python ${{ env.PYTHON_VERSION }}
      - name: Run Tox
        run: tox -v -e ${{ env.PREFIX_TOX }}${{ matrix.toxenv }}
  others:
    needs: linux
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, macos-13]
        toxenv: [pytestoldest, pytest50, pytest51, pytest60, pytest62]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{  env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{  env.PYTHON_VERSION }}
      - name: Install Pipx
        shell: bash
        run: pipx --version || python -m pip install --user pipx
      - name: Pip Cache
        id: pip-cache
        shell: bash
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{matrix.toxenv}}-${{ hashFiles('**/setup.cfg', '**/tox.ini') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{matrix.toxenv}}-
      - name: Install Tox
        run: pipx install tox --python ${{ env.PYTHON_VERSION }}
      - name: Run Tox
        run: tox -v -e ${{ env.PREFIX_TOX }}${{ matrix.toxenv }}
